const SET_CURRENT_SPEECH_STATE = Symbol("SET_CURRENT_SPEECH_STATE");
const SET_ACTIVE_AUDIO_FILE = Symbol("SET_ACTIVE_AUDIO_FILE");
const AXIOS_ERROR = Symbol("AXIOS_ERROR");
const AUDIO_FINISHED = Symbol("AUDIO_FINISHED");
const SAY = Symbol("SAY");
const SET_TEXT_TO_SAY = Symbol("SET_TEXT_TO_SAY");
const SET_ACTIVE_TRANSCRIPTION_ID = Symbol("SET_ACTIVE_TRANSCRIPTION_ID");

export {
  SET_CURRENT_SPEECH_STATE,
  SET_ACTIVE_AUDIO_FILE,
  AXIOS_ERROR,
  AUDIO_FINISHED,
  SAY,
  SET_TEXT_TO_SAY,
  SET_ACTIVE_TRANSCRIPTION_ID
};
